### ISSUE TITLE
Source and tag version mismatch for 0.6.1

### ISSUE THREAD

**Issue by ZimbiX** [matthewmcgarvey/selenium.cr#10]
When installing the shard:

> Shard "selenium" version (0.6.0) doesn't match tag version (0.6.1)

Same issue as https://github.com/naqvis/crystar/issues/9. I guess this is a common misstep

**Comment by matthewmcgarvey** [comment]
Thanks! I'll get a fix pushed out.

**Comment by matthewmcgarvey** [comment]
Should be fixed with `0.6.2`
