### ISSUE TITLE
Add ability to move to element

### ISSUE THREAD

**Issue by matthewmcgarvey** [matthewmcgarvey/selenium.cr#11]
https://gist.github.com/fernandes/9f59addd65a039b829f5a8a7bded796e

Right now you have to do manual calculations in order to move the cursor over an element. To trigger hover states that is way too complicated for users. Add a method that takes in an element and will move the cursor over it.

**Comment by matthewmcgarvey** [comment]
Completed by https://github.com/matthewmcgarvey/selenium.cr/commit/44cc85eaffa4b1c0bc7ad22c48012d2799552f2c

Thanks for figuring this out @fernandes! 🎉

**Comment by fernandes** [comment]
awesome! glad it helped! 😄 cheers!
