### ISSUE TITLE
localStorage Access

### ISSUE THREAD

**Issue by russ** [matthewmcgarvey/selenium.cr#19]
I really have no clue what it would actually take to get this implemented but it looks like it's supported on Selenium.
https://github.com/SeleniumHQ/selenium/blob/trunk/java/client/test/org/openqa/selenium/html5/LocalStorageTest.java#L42

It would be awesome to have access to that to help test bad login issues.

**Comment by matthewmcgarvey** [comment]
Looks like there's commands for accessing it https://github.com/SeleniumHQ/selenium/blob/da5331b162b65c70b6367d789c1d2bc1d2114a48/java/client/src/org/openqa/selenium/remote/html5/RemoteLocalStorage.java

This must not be part of the official webdriver spec.

Ruby implementation https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/rb/lib/selenium/webdriver/common/driver_extensions/has_web_storage.rb
