### ISSUE TITLE
Is there possible to navigate_to to several website synchronously use same session?

### ISSUE THREAD

**Issue by zw963** [matthewmcgarvey/selenium.cr#23]
e.g. i want to write a translate command line tools, i want to use selenium same firefox session to get the translate result from different website at same time(use Fiber), i could not find out how to do this in document, thanks.

**Comment by matthewmcgarvey** [comment]
@zw963 I'm not an expert in the w3 protocol. For that kind of question, you might look around at whether or not other language implementations can do it. Ruby's for example https://github.com/SeleniumHQ/selenium/tree/trunk/rb

If they can do it, I'm sure it can be done with this.

Let me know if it's possible and this library is missing something. Going to close this issue for now.
