### ISSUE TITLE
Consider port to windows?

### ISSUE THREAD

**Issue by zw963** [matthewmcgarvey/selenium.cr#31]
Please check following issue too.

https://github.com/crystal-lang/crystal/issues/5430#issuecomment-1537373838

Thanks

**Comment by zw963** [comment]
I add my app workflow for windows, get following error.

```
In lib\selenium\src\selenium\service.cr:99:20

 99 | process.signal(Signal::KILL)

                     ^-----------
Error: undefined constant Signal::KILL
```
[this](https://github.com/crystal-china/translater/actions/runs/4955270948/jobs/8864519942) is the log.

Following is the portable advice for Signal.

https://crystal-lang.org/api/1.8.1/Signal.html#portability

**Comment by jwoertink** [comment]
I just got this too on https://github.com/crystal-loot/exception_page/pull/40
